/* eslint-disable @next/next/no-sync-scripts */
import Navbar from "@/components/Navbar";
import "../styles/globals.css";
import "../styles/styles.css";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { LoadingBarProvider } from '../context/LoadingBarContext';
import CustomLoadingBar from '../components/LoadingBar';
import { ThemeProvider } from "../components/hooks/ThemeContext";
import LoadingBar from "react-top-loading-bar";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Login from '.'

function MyApp({ Component, pageProps }) {
  const [progress, setProgress] = useState(0);
  const router = useRouter();

  useEffect(() => {
    router.events.on("routeChangeStart", () => {
      setProgress(0);
    });

    router.events.on("routeChangeComplete", () => {
      setProgress(100);
    });

    router.events.on("routeChangeError", () => {
      setProgress(100);
    });
  }, [router.events]);

  return (
    <>
      <LoadingBar
        color="#f11946"
        progress={progress}
        waitingTime={400}
        onLoaderFinished={() => setProgress(0)}
        style={{ height: '5px' }}
      />
      <Head>
        <title>Link_Me</title>
        <meta name="description" content="Generated by create next app" />

        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://kit.fontawesome.com/64d58efce2.js"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"
        ></script>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
        />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>
      <LoadingBarProvider>
      <CustomLoadingBar />
      <ThemeProvider>
        <Component {...pageProps} />
        <Navbar />
        {/* <Login /> */}
        {/* <Dashboard /> */}
        
      </ThemeProvider>
      </LoadingBarProvider>
    </>
  );
}

export default MyApp;
